name: CI

on: 
  pull_request: 
    branches: [ develop ]
    
env:
  DEVELOPER_DIR: /Applications/Xcode_12.5.1.app

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1 # ソースコードをcheckout
    - name: Select Xcode version # Xcode 12.5.1 を使う
      run: sudo xcode-select -s '/Applications/Xcode_11.2.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build # シミュレーター向けにビルド
      run: xcodebuild -sdk iphonesimulator -configuration Debug build 
