name: SwiftLint

on: 
  pull_request: 
    branches: [ develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: docker://frmeloni/danger-swift-with-swiftlint:1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}